name: Run Ansible Playbook

on:
  workflow_dispatch:
  
  push:
    branches: [ "main" ]
    
jobs:
  run-ansible:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Test DNS resolution
        run: |
            ping -c 3 ${{ secrets.VCENTER_HOST }} || echo "Cannot resolve host"


      - name: Run Ansible Playbook
        env:
          HOSTNAME: ${{ secrets.VCENTER_HOSTNAME }}
          USERNAME: ${{ secrets.VCENTER_USERNAME }}
          PASSWORD: ${{ secrets.VCENTER_PASSWORD }}
          FOLDER: ${{ secrets.VCENTER_FOLDER }}
        run: |
          ansible-playbook GetNameofVM.yml \
            --extra-vars "hostname=$HOSTNAME username=$USERNAME password=$PASSWORD folder=$FOLDER"
