name: Run Ansible Playbook

on:
  workflow_dispatch:
  
  push:
    branches: [ "main" ]
    
jobs:
  run-ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Ansible
        run: |
            sudo apt-get update
            sudo apt-get install -y ansible python3-pip
            pip3 install requests pyvmomi
            ansible-galaxy collection install community.vmware


      - name: Run Ansible Playbook
        env:
          USERNAME: ${{ secrets.VCENTER_USERNAME }}
          PASSWORD: ${{ secrets.VCENTER_PASSWORD }}
          FOLDER: ${{ secrets.VCENTER_FOLDER }}
        run: |
          export hostname: ${{ secrets.VCENTER_HOSTNAME }}
          ansible-playbook GetNameofVM.yml \
            --extra-vars "username=$USERNAME password=$PASSWORD folder=$FOLDER"
